blocks:
  - name: LoadEmployers
    step:
      integration: f2d3c7ba-3924-4cd0-aa6b-78a28508a4fd
      postgres:
        body: |-
          SELECT
           e.id,
           e.company_nickname,
           e.legal_name,
           em.first_name,
           em.last_name,
           e.phone,
           em.email
          from employers e inner join employer_memberships em on e.primary_contact_id = em.id;
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 5a6cefaf-d3ee-40a2-8762-ab7fae2df033
  name: AllEmployers
  organization: 3ca4034f-78ef-4d5e-acb2-6c6948e47fde
trigger:
  application:
    id: 63d454db-a7b2-42e7-a0fa-23462fa3e072
    options:
      executeOnPageLoad: true
    pageId: 091381a9-bd98-41dd-8fbe-268e61905418
