blocks:
  - name: LoadEmployer
    step:
      integration: f2d3c7ba-3924-4cd0-aa6b-78a28508a4fd
      postgres:
        body: |-
          SELECT
            e.*,
            pdp.id as pdp_id,
          	pdp.status
          	from employers e inner join plan_design_proposals pdp on e.id = pdp.employer_id where e.id={{EmployersTable.selectedRow.id}} limit 1
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 398fe272-9671-4813-8032-7cbb11d24a13
  name: SingleEmployer
  organization: 3ca4034f-78ef-4d5e-acb2-6c6948e47fde
trigger:
  application:
    id: 63d454db-a7b2-42e7-a0fa-23462fa3e072
    pageId: 091381a9-bd98-41dd-8fbe-268e61905418
